name: Scraping Web

on:
  schedule:
    - cron: '0 0 * * 0' 
  workflow_dispatch:  

jobs:
  scrape_web:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Git
      run: |
        git config --global user.email "gaspargomez2000@outlook.com"
        git config --global user.name "ggomez0"

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Instalar dependencias
      run: |
        pip install -r scraping/requirements.txt

    - name: Ejecutar tarea de scraping
      run: |
        python scraping/scrapingjson.py

    - name: Subir json generado
      run: |
        git checkout main
        git add .
        git commit -m "JSON generado diario"
        git push origin main
